### PR TITLE
Replace wfRunHooks with Hooks::run

### PR DESCRIPTION
**Pull request by paladox**
MediaWiki 1.32 removed wfRunHooks so replace with Hooks::run

### PR Submission:

All PR's welcome, even those without an Issue

* [ ] Have tested this PR and it adds a feature or fixes an issue noted below.

### CODE REVIEW

**Comment by Hutchy68** [comment]
Well, I’m scratching my head as MW is now on JQuery 3+. Pivot breaks on MW 1.32 js but is not breaking on Foreground which is using the same version of foundation 5.3.3.

**Comment by paladox** [comment]
pivot js works for me on https://meta.miraheze.org/w/index.php?title=Miraheze&useskin=pivot

**Comment by paladox** [comment]
Oh, the action menu failed.

Console log shows ReferenceError: Can't find variable: jQuery

**Comment by Hutchy68** [comment]
Yep supposedly foundation 5 doesn’t play nice with jQuery 3+

**Comment by paladox** [comment]
I guess we should update to foundation 6?

**Comment by Hutchy68** [comment]
Well long term was my plan. There are a lot of backwards compatibility issues that will need to be addressed. 

Adding jQuery 2.4 as a top loading alternative jQuery fixes it. Although it’s pretty bad to load 2 versions of jQuery 🤦🏼‍♂️.

What I can’t wrap my head around is why Foreground works! I know I updated 5.3.3 to 5.3.3master in Pivot to address .load(function with .on(“load”, function...  it must be something to do with off-canvas.  I even dropped all of pivot’s js loads and matched them to Foreground. Still broken.

**Pull request merged**
